[viewer]
    Title = "Go语言博客"
    Description = "Go语言博客"
    Logo = "/resource/images/logo.png"
    Navigation = ["首页","/", "GO语言","/golang", "归档","/pigeonhole", "关于","/about"]
    Bilibili = "https://space.bilibili.com/473844125"
    Zhihu = "https://www.zhihu.com/people/ma-shen-zhi-lu"
    Avatar = "https://avatars.githubusercontent.com/u/54505023?s=400&u=965ad764e3376feb406d986a4c679aa62b9dafcb&v=4"
    UserName = "MacReeee"
    UserDesc = "长得非常帅的程序员"
[system]
    CdnURL = "https://static.mszlu.com/goblog/es6/md-assets"
    QiniuAccessKey = "xNQtXgPky0yHX0MjHEHZr1MSLZSORWFeCa4-lpwb"
    QiniuSecretKey = "MYWaBkx4mE0_n5A-hgMGaVRWUziTIWCOXKFSOylS"
    Valine = true
    ValineAppid = "IhwftlBWp361rBZhKN2aEIV2-gzGzoHsz"
    ValineAppkey = "u6MGd4NhP2jy42mqKYMCFh4b"
    ValineServerURL = "https://ihwftlbw.lc-cn-n1-shared.com"